image:
  repository: quay.io/ukhomeofficedigital/callisto-accruals-person-consumer
  tag: latest
  pullPolicy: Always

service:
  port: 9090

kafka:
  defaultTopic: callisto-person-people
  identity: accruals-person-consumer
  mskSecretKeyRefName: callisto-prod-msk
  bootstrapSecretKeyRefName: callisto-prod-bootstrap