image:
  repository: quay.io/ukhomeofficedigital/callisto-accruals-person-consumer
  tag: latest
  pullPolicy: Always

service:
  port: 9090

deploymentAnnotations:
  downscaler/uptime: Mon-Fri 08:00-20:00 Europe/London

kafka:
  defaultTopic: callisto-person-people
  identity: accruals-person-consumer
  mskSecretKeyRefName: callisto-test-msk
  bootstrapSecretKeyRefName: callisto-test-bootstrap